config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comment
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  	@articles = Article.all
  end

  def new
  	@article = Article.new
  end

  def edit
  	@article = Article.find(params[:id])
  end

  def delete
  end

  def show
    @article = Article.find(params[:id])
  end

  private
  def param_article
  	params.require(:article).permit(:article_id, :title, :content, :status)
  end
end

app/controllers/comments_controller.rb
class CommentController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/delete.html.erb
<h1>ArticleController#delete</h1>
<p>Find me in app/views/article_controller/delete.html.erb</p>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= form_for @foto, html: {class: "nifty_form"} do |f| %>
  <%= f.label "title" %>
  <%= f.text_field :title %>
  <%= f.label "content" %>
  <%= f.text_field :content %>
  <%= f.label "status" %>
  <%= f.text_field :status %>
  <%= f.submit "Save" %>
<% end %>

app/views/articles/new.html.erb
<h1>Upload Your Article</h1>
<%= form_for @article do |form| %>
  <%= form.label :Title %>
  &nbsp;
  &nbsp;
  &nbsp;

  <%= form.text_field :article_title %>
  <br/>
   <br/>

  <%= form.label :Content %>
  <%= form.text_area :article_content, cols: 30, rows: 10 %>
  <br/>
  <%= form.label :Status %>
  &nbsp;
  &nbsp;
  <%= form.radio_button :article_status, "Active" %>
  <%= label :article_status, 'Active' %>
  <%= form.radio_button :article_status, "Hide" %>
  <%= label :article_status, 'Hide' %>
  <br/>
  <br/>
  <%= form.submit "Save" %>
<% end %> 


    

app/views/comments/delete.html.erb
<h1>CommentController#delete</h1>
<p>Find me in app/views/comment_controller/delete.html.erb</p>

app/views/comments/edit.html.erb
<h1>CommentController#edit</h1>
<p>Find me in app/views/comment_controller/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>CommentController#index</h1>
<p>Find me in app/views/comment_controller/index.html.erb</p>

app/views/comments/new.html.erb
<h1>CommentController#new</h1>
<p>Find me in app/views/comment_controller/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Articles</title>
<p>Find me in app/views/article_controller/index.html.erb</p>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>
<nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Task_5</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="nav navbar-nav">
                <li><%= link_to "Home" , articles_path %></li>
                <li><%= link_to "Upload" , new_article_path %></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
 <%= yield %>
</div>
</body>
</html>